### ISSUE TITLE
Issue when loading angular-esri-loader prior to esri-map.

### ISSUE THREAD

**Issue by robertvanGilst** [TheKeithStewart/angular-esri-components#21]
I've got an issue when using esri-map in my route-enabled solution. I've made a service where I use angular-ersi-loader to load the ArcGIS Javascript API in the constructor of the service. On a page longer down the tree I have an esri-map and when I follow the flow it works fine.

But when I refresh the page and start on the longer down the tree I get the following error: 
> error: The ArcGIS API for JavaScript is already loaded.

I can recreate it with the following code, I cannot add the load in the map-init, because it already is loaded in another route.:

```
import { Component, OnInit } from '@angular/core';
import { EsriLoaderService } from 'angular-esri-loader';

@Component({
  selector: 'app-already-loaded',
  template: `
    <esri-map [mapProperties]="mapProperties" [mapViewProperties]="mapViewProperties" (mapInit)="onMapInit($event)"></esri-map>
  `,
  styleUrls: ['./already-loaded.component.css'],
  providers: [EsriLoaderService]
})
export class AlreadyLoadedComponent implements OnInit {
  mapProperties: __esri.MapProperties = {
    basemap: 'dark-gray'
  };
  mapViewProperties: __esri.MapViewProperties = {
    center: [-118, 34.5],
    zoom: 8
  };
  map: __esri.Map;
  mapView: __esri.MapView;

  constructor(private esriLoader: EsriLoaderService) { 
    this.esriLoader.load();
  }

  onMapInit(mapInfo: {map: __esri.Map, mapView: __esri.MapView}) {
    this.map = mapInfo.map;
    this.mapView = mapInfo.mapView;
  }

  ngOnInit() {
  }
}
```

**Comment by robertvanGilst** [comment]
I think I have create a fix for this problem:

Add a check in the esri-map-service.ts to check whether the ArcGIS Javascript API has been loaded like this:
```private load() {
    return new Promise(() => {
      if (this.esriLoader.isLoaded) { return; }
      return this.esriLoader.load({
        // the specific version of the API that is to be used
        url: 'https://js.arcgis.com/4.3/'
      });
    })
  }

  loadMap(mapProperties: __esri.MapProperties, mapViewProperties: __esri.MapViewProperties, mapEl: ElementRef) {
    return this.load().then(() => {
      return this.esriLoader.loadModules([
        'esri/Map', 'esri/views/MapView'
      ]).then(([
...
```
If you like I can create a pull request with the code, so you'll be able to check it.

**Comment by TheKeithStewart** [comment]
This should no longer be an issue once #25 is complete

**Comment by TheKeithStewart** [comment]
@robertvanGilst 

I apologize for taking so long to respond to this issue. I'm trying to get this library back up to speed now and will be staying on top of the Issues logged.

When I initially read this issue I somehow misunderstood it. Completing the issue mentioned earlier will not solve this.

Is the above fix actually working for you? I've tried it myself and it does not resolve the error. I'm considering a different approach. I'm assuming that you are loading the ArcGIS JSAPI script because you want to use a different version than the library is using. If this is the case, what about having the map component take an Input that will allow you to dictate the version of the script to load? This way you don't have to worry about two load scripts to be run. There would just be one and it would be either than version you requested or the default for the library.

Please let me know what you think.

**Comment by robertvanGilst** [comment]
@TheKeithStewart 

I think we should close this issue. It is so far in the past that I cannot recall which project I was working in and what I did anymore ;-)

**Comment by TheKeithStewart** [comment]
Sounds good, @robertvanGilst. Please let me know if it come up again for you.
